#!/bin/bash


for BYTEVAL in 2 4 8 16 32 64 128 256 512 1024 2048
do 
	printf $BYTEVAL + " Bytes\n"
	time ./copycat -b $BYTEVAL -o output.txt input.txt input1.txt input2.txt input3.txt input4.txt
done 